module.exports = {
  STATUS: {
    SUCCESS: "SUCCESS",
    ERROR: "FAILURE",
    EXCEPTION: "EXCEPTION",
  },
  CODE: {
    OK: "200",
    NON_AUTHORITIVE_INFORMATION: "203",
    PARTIAL_CONTENT: "206",
    BAD_REQUEST: "400",
    UNAUTHORIZED: "401",
    FORBIDDEN: "403",
    INTERNAL_SERVER_ERROR: "500",
    SERVICE_UNAVAILABLE: "503",
  },

  privateKEY: `-----BEGIN RSA PRIVATE KEY-----
MIIBOQIBAAJBAKWSRFEmw9e5g2uoboR+U+3hrlxQsYHbDtEQ0IU5bSWLyRYLLKe3
q1u0bp2iMNVRjNhjYC0FLnR8V3qjtLmaWVMCAwEAAQJAO6SM547HTZaOOOHbre6z
3SVG4gpPZy+6DqW398XQA43a9aCt9DARfYVvp9j9ZHxKizmNFzxP4AWFgLq9V93z
gQIhAM8DIHLnQpSYU7CMR9u+kxBI72p4Us6WKWObds5QaVAbAiEAzMCjYMet2UiN
GjnbtPmqHFwNauWb1D2EbVdSZaUv3ykCIE86CR8wtuCb89urtIy7QRmIcGi1KCv8
eFaw1yVazRNlAiAHS4nGpfakujgEyjDwxsBv2DvGJj4iFrsEJktSQctt2QIgTLca
v8oQEfoKLHitbGPyRL8ZUwatgZUO8v4XG8f4wfI=
-----END RSA PRIVATE KEY-----`,

  publicKEY: `-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKWSRFEmw9e5g2uoboR+U+3hrlxQsYHb
DtEQ0IU5bSWLyRYLLKe3q1u0bp2iMNVRjNhjYC0FLnR8V3qjtLmaWVMCAwEAAQ==
-----END PUBLIC KEY-----`,
};
